fix mm_2.md
hust-open-atom-club/linux-insides-zh pull request #289
Opened 2024-07-21 02:34 UTC by suqingfa

修改部分描述不准确的地方。

2024-07-24 14:48 UTC, mudongliang requested changes

2024-07-24 14:48 UTC, mudongliang commented on MM/linux-mm-2.md
> +不支持时调用 `__flush_tlb` 更新 `cr3` 寄存器。在这步结束之后 `__early_set_fixmap` 函数就执行完了，我们又可以回到 `__early_ioremap` 的实现了。因为我们为给定的地址设定了固定映射区域，我们需要将 I/O 重映射的区域的基虚拟地址用 `slot` 下标保存在 `prev_map` 数组中。
“不支持时调用”， 这是typo吗？

2024-07-27 09:18 UTC, suqingfa commented on MM/linux-mm-2.md
> +不支持时调用 `__flush_tlb` 更新 `cr3` 寄存器。在这步结束之后 `__early_set_fixmap` 函数就执行完了，我们又可以回到 `__early_ioremap` 的实现了。因为我们为给定的地址设定了固定映射区域，我们需要将 I/O 重映射的区域的基虚拟地址用 `slot` 下标保存在 `prev_map` 数组中。
不是。这是对下面这段代码解释，原文是 If a CPU supports the invlpg instruction, we call the __flush_tlb_single macro which expands to the call of __native_flush_tlb_single, or call __flush_tlb which just updates the cr3 register as we have seen。CPU 支持 invlpg 指令的时候调用 __flush_tlb_single，不支持 invlpg 指令的时候调用 __flush_tlb 更新 cr3。我不懂译文为啥要翻译成"`__flush_tlb` 的调用知识更新了 `cr3` 寄存器"。

```
static inline void __flush_tlb_one(unsigned long addr)
{
        if (cpu_has_invlpg)
                __flush_tlb_single(addr);
        else
                __flush_tlb();
}
```

2024-07-28 05:42 UTC, mudongliang requested changes

2024-07-28 05:42 UTC, mudongliang commented on MM/linux-mm-2.md
> +不支持时调用 `__flush_tlb` 更新 `cr3` 寄存器。在这步结束之后 `__early_set_fixmap` 函数就执行完了，我们又可以回到 `__early_ioremap` 的实现了。因为我们为给定的地址设定了固定映射区域，我们需要将 I/O 重映射的区域的基虚拟地址用 `slot` 下标保存在 `prev_map` 数组中。
我理解了，“不支持时”后面应该有一个逗号，我建议修改为“否则，调用”

2024-07-28 14:28 UTC, suqingfa commented on MM/linux-mm-2.md
> +不支持时调用 `__flush_tlb` 更新 `cr3` 寄存器。在这步结束之后 `__early_set_fixmap` 函数就执行完了，我们又可以回到 `__early_ioremap` 的实现了。因为我们为给定的地址设定了固定映射区域，我们需要将 I/O 重映射的区域的基虚拟地址用 `slot` 下标保存在 `prev_map` 数组中。
修改了。

2024-07-28 14:29 UTC, mudongliang approved these changes

2024-07-28 14:29 UTC, merged